services:
  firebird:
    image: jacobalberty/firebird:v0.0.2
    environment:
      FIREBIRD_DATABASE: 'database.fdb'
      ISC_PASSWORD: 'masterkey'
      EnableLegacyClientAuth: 'true'
    ports:
      - "3051:3050"